### PR TITLE
Fix endpoint expansion when an operation is opened programmatically

### PR DESCRIPTION
**Pull request by deiteris**

### CODE REVIEW

**Comment by deiteris** [comment]
@TwoPlusTwoOne, @carowright, @jarrodek, could you review this one please?

**Review by TwoPlusTwoOne — CHANGES_REQUESTED** [review]
Hi @deiteris, thanks for the contribution. Could you add a test case to this addition?

**Comment by deiteris** [comment]
@TwoPlusTwoOne I've added the test case, you can verify that it works by commenting out my piece of code.

Just for history and to clarify the issue a bit, here's the gif that shows what it looks like. The endpoint method is being set by `element.selected = "#id"`, but the parent is not being expanded to show the selection.
gh_issue

**Review by TwoPlusTwoOne — APPROVED** [review]

**Review by TwoPlusTwoOne — CHANGES_REQUESTED** [review]
Sorry one last thing, could you bump the version please?

**Comment by TwoPlusTwoOne** [comment]
Yes that would be best, thank you very much. I hadn't seen the base branch

**Pull request closed without merging**
